app = 'hardy'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8884
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
